export enum AnalyticsSagaActions {
  SEND_ANALYTICS = "SEND_ANALYTICS",
  SAVED_ON_ANALYTICS_A = "SAVED_ON_ANALYTICS_A",
  SAVED_ON_ANALYTICS_B = "SAVED_ON_ANALYTICS_B",
  UNABLE_TO_SAVE_ANALYTICS_A = "UNABLE_TO_SAVE_ANALYTICS_A",
  UNABLE_TO_SAVE_ANALYTICS_B = "UNABLE_TO_SAVE_ANALYTICS_B",
}
