export enum CardsSagaActions {
  FETCH_CARDS_SAGA = "FETCH_CARDS_SAGA",
  DELETE_CARDS_SAGA = "DELETE_CARDS_SAGA",
  UPDATE_CARD_SAGA = "UPDATE_CARD_SAGA",
  HIDE_DELETE_MODAL = "HIDE_DELETE_MODAL",
  INPUT_SEARCH = "INPUT_SEARCH",
}
